# Generated by Django 4.0.4 on 2022-05-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tododb',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tododb',
            name='date_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
