# Generated by Django 4.0.4 on 2022-05-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_tododb_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tododb',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
