# Generated by Django 4.1.1 on 2022-11-20 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0005_alter_tododb_content_alter_tododb_header_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tododb',
            options={'ordering': ['date_add'], 'verbose_name': 'Todoшка', 'verbose_name_plural': 'Todoшки'},
        ),
        migrations.AlterField(
            model_name='tododb',
            name='slave',
            field=models.CharField(max_length=100, verbose_name='Виконавець'),
        ),
        migrations.CreateModel(
            name='Complate_task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('complate', models.BooleanField(default=False)),
                ('users_complate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Закінчена задача',
                'verbose_name_plural': 'Закінчені задачі',
                'ordering': ['date_add'],
            },
        ),
        migrations.CreateModel(
            name='Cancel_task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('complate', models.BooleanField(default=False)),
                ('users_cancel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Отмена',
                'verbose_name_plural': 'Отмена',
                'ordering': ['date_add'],
            },
        ),
        migrations.AddField(
            model_name='tododb',
            name='cancel',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='dashboard.cancel_task'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tododb',
            name='complate',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='dashboard.complate_task'),
            preserve_default=False,
        ),
    ]
