# Generated by Django 4.1.1 on 2022-11-24 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_tododb_cancel_alter_tododb_complate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tododb',
            name='cancel',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='dashboard.cancel_task'),
        ),
        migrations.AlterField(
            model_name='tododb',
            name='complate',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='dashboard.complate_task'),
        ),
    ]
