# Generated by Django 4.1.1 on 2022-11-27 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_remove_complate_task_users_complate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tododb',
            name='cancel',
        ),
    ]
